name: cpepmatch
channels:
  - conda-forge
  - defaults
  - salilab
dependencies:
  - python=3.7.11
  - numpy
  - scipy
  - matplotlib
  - ipython
  - pandas
  - sympy
  - nose
  - biopython
  - mdanalysis
  - conda-forge::vmd-python
  - salilab::modeller